### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by reinder42** [m1a7/MFS-Pattern-Part2#1]
Hi there,

I would have appreciated it if you would have asked for permission to use the copyrighted image from LearnAppMaking.com in your tutorial and here in this repository. You can't just go about lifting images from web pages. It's not OK to just provide a link back. This repository made available under the MIT license, which means you're now also open sourcing my copyrighted image. I do not permit that, and request that you remove the image from this repository and from your tutorial [here](https://web-center.su/паттерн-mfs-для-табличных-представлений/) and [here](https://habr.com/ru/post/539590/?utm_campaign=539590&utm_source=habrahabr&utm_medium=rss).

—Reinder

**Comment by m1a7** [comment]
Good afternoon.
I'm sorry, I'm deleting it now.

**Comment by reinder42** [comment]
Thanks!
